<?php

/**
 * @file
 * su_course_tags.module
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */

function stanford_courses_default_list_viewfield_block_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  /*
  // On the ECK entity, if the instructor person is set, use that to display.
  if ($entity->get('field_instructor_person')->count()) {
    unset($build['title']);
    return;
  }
  */


  /** @var \Drupal\Core\Field\FieldItemList $instructor_role_list */
  /*
  $instructor_role_list = $entity->get('field_instructor_role');
  if ($instructor_role_list->count()) {
    $build['title'][0]['#context']['value'] .= ' (' . $instructor_role_list->getString() . ')';
  }
  */
}
