<?php
/**
 * @file
 * File description
 *
 * Long description
 */

/**
 * Implements hook_help().
 */
function stanford_courses_tag_translate_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module.
    case 'admin/help#course-tag-translate':
      return '<p>' . t('Ask John !email', array('!email' => l("jbickar@stanford.edu","mailto://jbickar@stanford.edu"))) . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function stanford_courses_tag_translate_menu() {

  // Landing page.
  $items['admin/config/stanford/courses/tag-translate'] = array(
    'title' => 'Stanford Courses Tag Translate',
    'page callback' => 'stanford_courses_tag_translate_settings',
    'page arguments' => array(),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => "stanford_courses_tag_translate.pages.inc",
  );

  return $items;
}


/*
 * Implements hook_ctools_plugin_directory().
 */
function stanford_courses_tag_translate_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
}

/**
 * Gets all the translations out of the database keyed with the tag.
 * @return [type] [description]
 */
function stanford_courses_tag_translate_get_translation_table() {
  $ttable = &drupal_static(__FUNCTION__);
  if ($ttable) {
    return $ttable;
  }
  $results = db_select("stanford_courses_tag", "sct")
              ->fields("sct", array("ctag", "chuman"))
              ->execute()
              ->fetchAllAssoc("ctag");

  ksort($results, SORT_NATURAL, SORT_FLAG_CASE);
  $ttable = $results;
  return $ttable;
}
