stanford_courses_importer.importer_settings:
  type: config_entity
  label: 'Course Importer settings.'
  mapping:
    urls:
      type: sequence
      label: 'Importer URLs'
      sequence:
        type: string
        label: 'Importer URL'
