<?php

use Drupal\Core\Form\FormStateInterface;
/**
 * @file
 * stanford_courses_importer.module
 */

 /**
 * Implements hook_form_FORM_ID_alter().
 * config-page-stanford-courses-importer-form config-pages-form
 *
 * Alter the config form to add the migrate_tools UI.
 */
function stanford_courses_importer_form_config_pages_stanford_courses_importer_form_alter(array &$form, FormStateInterface $form_state) {
  $user = \Drupal::currentUser();
  $form['actions']['#type'] = 'fieldset';

  $form['actions']['import'] = [
    '#type' => 'submit',
    '#value' => t('Save & Import'),
    '#name' => 'op',
    '#button_type' => "primary",
    '#submit' => [
      "::submitForm",
      "::save",
      "stanford_courses_importer_form_config_pages_stanford_courses_importer_form_alter_submit",
    ],
  ];
  return $form;
}
