<?php
/**
 * @file
 * Code for the Stanford Courses Person Reference Views feature.
 */

include_once 'stanford_courses_person_reference_views.features.inc';

/**
 * Implements hook_form_alter().
 */
function stanford_courses_person_reference_views_form_alter(&$form, &$form_state, $form_id) {

    // We only want views exposed forms
    if ($form_id !== "views_exposed_form") {
        return;
    }

    // We only want the ones on the course search views.
    if ($form['#id'] !== 'views-exposed-form-courses-reference-search-page' && $form['#id'] !== 'views-exposed-form-courses-search-page') {
        return;
    }

    // Make sure the subject value is there.
    if (!isset($form['field_s_course_subject_value'])) {
        return;
    }

    // We have the form we want here. Change the programs option from a text field into a select option.
    $options = stanford_courses_person_reference_views_get_subject_options();
    $field = &$form['field_s_course_subject_value'];
    $field['#type'] = 'select';
    $field['#options'] = $options;
    unset ($field['#size']);

}

/**
 * Returns a list of subject options.
 * @return array of options keyed with keywords.
 */
function stanford_courses_person_reference_views_get_subject_options() {
    $options = array();
    $options[''] = '- ' . t('Any') . ' -';

    $result = db_select('field_data_field_s_course_subject', 'fdfscs', array('DISTINCT' => TRUE))
        ->fields('fdfscs', array('field_s_course_subject_value'))
        ->orderBy('field_s_course_subject_value', 'ASC')
        ->execute()
        ->fetchAllAssoc('field_s_course_subject_value');

    $keys1 = $keys2 = array_keys($result);
    $keys = array_combine($keys1, $keys2);
    return array_merge($options, $keys);
}
