<?php
/**
 * @file
 * Code for the Stanford Courses Person Reference Views feature.
 */

include_once 'stanford_courses_person_reference_views.features.inc';

/**
 * Implements hook_form_alter().
 */
function stanford_courses_person_reference_views_form_alter(&$form, &$form_state, $form_id) {

  // We only want views exposed forms
  if ($form_id !== "views_exposed_form") {
    return;
  }

  // We only want the ones on the course search views.
  if ($form['#id'] !== 'views-exposed-form-courses-reference-search-page' && $form['#id'] !== 'views-exposed-form-courses-search-page') {
    return;
  }

  // Make sure the subject value is there.
  if (!isset($form['field_s_course_program_tid'])) {
    return;
  }

  $field = &$form['field_s_course_program_tid'];
  $field['#type'] = 'checkboxes';
  unset($field['#size']);
  unset($field['#multiple']);

}
